src/Shop/MainBundle/Entity/Action.php
<?php

namespace Shop\MainBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class Action
 * @package Shop\MainBundle\Entity]
 */
class Action extends AbstractEntity
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $description;

    /**
     * @var string
     */
    private $thumbImageFileName;

    /**
     * @var string
     */
    private $imageFileName;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Action
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Action
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set thumbImageFileName
     *
     * @param string $thumbImageFileName
     * @return Action
     */
    public function setThumbImageFileName($thumbImageFileName)
    {
        $this->thumbImageFileName = $thumbImageFileName;

        return $this;
    }

    /**
     * Get thumbImageFileName
     *
     * @return string 
     */
    public function getThumbImageFileName()
    {
        return $this->thumbImageFileName;
    }

    public function getThumbImage(){
        return $this->getFile('thumbImageFileName');
    }

    public function setThumbImage($file = null){
        return $this->setFile('thumbImageFileName', $file);
    }

    public function getThumbImageUrl(){
        return $this->getFileUrl($this->getThumbImageFileName()) ?: $this->getImageUrl();
    }

    /**
     * Set imageFileName
     *
     * @param string $imageFileName
     * @return Action
     */
    public function setImageFileName($imageFileName)
    {
        $this->imageFileName = $imageFileName;

        return $this;
    }

    /**
     * Get imageFileName
     *
     * @return string 
     */
    public function getImageFileName()
    {
        return $this->imageFileName;
    }

    public function getImage(){
        return $this->getFile('imageFileName');
    }

    public function setImage($file = null){
        return $this->setFile('imageFileName', $file);
    }

    public function getImageUrl(){
        return $this->getFileUrl($this->getImageFileName());
    }

}

src/Shop/MainBundle/Controller/DefaultController.php
<?php

namespace Shop\MainBundle\Controller;

use Shop\MainBundle\Entity\Address;
use Weasty\Bundle\CommonBundle\Entity\Settings;
use Sonata\MediaBundle\Model\MediaInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class DefaultController
 * @package Shop\MainBundle\Controller
 */
class DefaultController extends Controller
{

    public function indexAction()
    {

        $request_form = $this->createFormBuilder(null, array(
                'attr' => array(
                    'class' => 'request-form form-box',
                ),
            ))
            ->add('request_customer_name', 'text', array(
                'label' => 'КАК К ВАМ ОБРАЩАТЬСЯ*',
                'required' => true,
                'attr' => array(
                    'class' => 'customer-name',
                ),
            ))
            ->add('request_customer_phone', 'text', array(
                'label' => 'ТЕЛЕФОН*',
                'attr' => array(
                    'class' => 'customer-phone',
                ),
            ))
            ->add('request_customer_email', 'text', array(
                'label' => 'E-MAIL',
                'attr' => array(
                    'class' => 'customer-email',
                ),
            ))
            ->add('save', 'submit', array(
                'label' => 'ОТПРАВИТЬ ЗАЯВКУ',
                'attr' => array(
                    'class' => 'submit-btn',
                ),
            ))
            ->getForm();

//        $footer_request_form = $this->createFormBuilder(null, array(
//                'attr' => array(
//                    'class' => 'request-form form-box',
//                ),
//            ))
//            ->add('footer_request_customer_name', 'text', array(
//                'label' => 'КАК К ВАМ ОБРАЩАТЬСЯ*',
//                'required' => true,
//                'attr' => array(
//                    'class' => 'customer-name',
//                ),
//            ))
//            ->add('footer_request_customer_phone', 'text', array(
//                'label' => 'ТЕЛЕФОН*',
//                'attr' => array(
//                    'class' => 'customer-phone',
//                ),
//            ))
//            ->add('footer_request_customer_email', 'text', array(
//                'label' => 'E-MAIL',
//                'attr' => array(
//                    'class' => 'customer-email',
//                ),
//            ))
//            ->add('save', 'submit', array(
//                'label' => 'ОТПРАВИТЬ ЗАЯВКУ',
//                'attr' => array(
//                    'class' => 'submit-btn',
//                ),
//            ))
//            ->getForm();

        return $this->render('ShopMainBundle:Default:index.html.twig', array(
            'request_form' => $request_form->createView(),
//            'footer_request_form' => $footer_request_form->createView(),
//            'why_us_items' => $this->getWhyUsItems(),
            'benefits' => $this->getBenefits(),
            'reviews' => $this->getReviews(),
//            'how_we_items' => $this->getHowWeItems(),
//            'problems' => $this->getProblems(),
//            'solutions' => $this->getSolutions(),
            'addresses' => $this->getAddresses(),
        ));

    }

    /**
     * @return BinaryFileResponse
     */
    public function faviconAction(){

        $settings = $this->get('shop_main.settings.resource')->getSettings();
        if(!$settings instanceof Settings){
            throw $this->createNotFoundException('Settings not found');
        }

        $media = ($settings->getFavicon() ?: $settings->getLogo());
        if (!$media instanceof MediaInterface) {
            throw $this->createNotFoundException('Favicon not found');
        }

        /**
         * @var $mediaService \Sonata\MediaBundle\Provider\Pool
         */
        $mediaService = $this->get('sonata.media.pool');
        $provider = $mediaService->getProvider($media->getProviderName());

        $format = ($settings->getFavicon() ? 'medium' : 'favicon');
        $format = $provider->getFormatName($media, $format);

        /**
         * @var $adapter \Sonata\MediaBundle\Filesystem\Local
         */
        $adapter = $provider->getFilesystem()->getAdapter();
        $filename = sprintf('%s/%s',
          $adapter->getDirectory(),
          $provider->generatePrivateUrl($media, $format)
        );

        $response = new BinaryFileResponse($filename);
        return $response;

    }

    /**
     * @param Request $request
     * @return JsonResponse
     */
    public function processRequestAction(Request $request){

        $this->sendEmail($request);
        return new JsonResponse('Спасибо, заявка принята! В ближайшее время с Вами свяжется наш менеджер для уточнения деталей.');

    }

    /**
     * @param Request $request
     * @return JsonResponse
     */
    public function orderProposalAction(Request $request){

        $this->sendEmail($request);
        return new JsonResponse('Спасибо, заявка принята! В ближайшее время с Вами свяжется наш менеджер для уточнения деталей.');

    }

    /**
     * @param Request $request
     * @return JsonResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function callbackAction(Request $request){

        if($request->getMethod() == 'POST'){

            $this->sendEmail($request);
            return new JsonResponse('Спасибо, заявка принята! В ближайшее время с Вами свяжется наш менеджер для уточнения деталей.');

        } else{

            return $this->render('ShopMainBundle:Default:callback.html.twig');

        }

    }

    protected function sendEmail(Request $request){

        /**
         * @var $settings \Weasty\Bundle\CommonBundle\Entity\Settings
         * @var $contacts \Shop\MainBundle\Data\ShopContactsResource
         */
        $settings = $this->get('shop_main.settings.resource')->getSettings();
        $contacts = $this->get('shop_main.contacts.resource');

        $proposal_information = null;
        $proposal_name = $request->get('name');
        $proposal_price = $request->get('price');

        if($proposal_name && $proposal_price){
            $proposal_information = $proposal_name . ', ' . $proposal_price;
        }

        $twig = clone $this->get('twig');
        $twig->setLoader(new \Twig_Loader_String());
        $data = array(
            'customer_name' => $request->get('customer_name'),
            'customer_phone' => $request->get('customer_phone'),
            'customer_email' => $request->get('customer_email'),
            'customer_comment' => $request->get('comment'),
            'order_information' => $proposal_information,
            'shop_name' => $settings->getName(),
            'shop_address' => $settings->getAddress(),
            'shop_phone' => implode(', ', $contacts->getPhones()),
            'shop_email' => $settings->getEmail(),
        );

        if($data['customer_email']){

            $message = \Swift_Message::newInstance()
                ->setSubject($settings->getName())
                ->setFrom($settings->getEmail())
                ->setTo($data['customer_email'])
                ->setBody($twig->render($settings->getCustomerEmailTemplate(), $data), 'text/html');

            $this->get('mailer')->send($message);

        }

        if($settings->getManagerEmail()){

            $message = \Swift_Message::newInstance()
                ->setSubject($settings->getName())
                ->setFrom($settings->getEmail())
                ->setTo($settings->getManagerEmail())
                ->setBody($twig->render($settings->getManagerEmailTemplate(), $data), 'text/html');

            $this->get('mailer')->send($message);

        }

        if($settings->getAdminEmail()){

            $message = \Swift_Message::newInstance()
                ->setSubject($settings->getName())
                ->setFrom($settings->getEmail())
                ->setTo($settings->getAdminEmail())
                ->setBody($twig->render($settings->getAdminEmailTemplate(), $data), 'text/html');

            $this->get('mailer')->send($message);

        }

    }

    /**
     * @return array
     */
    protected function getProblems(){
        return $this->getDoctrine()->getManager()->getRepository('ShopMainBundle:Problem')->findAll();
    }

    /**
     * @return array
     */
    protected function getSolutions(){
        return $this->getDoctrine()->getManager()->getRepository('ShopMainBundle:Solution')->findAll();
    }

    /**
     * @return array
     */
    protected function getWhyUsItems(){
        return $this->getDoctrine()->getManager()->getRepository('ShopMainBundle:WhyUsItem')->findAll();
    }

    /**
     * @return array
     */
    protected function getHowWeItems(){
        return $this->getDoctrine()->getManager()->getRepository('ShopMainBundle:HowWeItem')->findAll();
    }

    /**
     * @return array
     */
    protected function getReviews(){
        return $this->getDoctrine()->getManager()->getRepository('ShopMainBundle:Review')->findAll();
    }

    /**
     * @return array
     */
    protected function getBenefits(){
        return $this->getDoctrine()->getManager()->getRepository('ShopMainBundle:Benefit')->findAll();
    }

    /**
     * @return array
     */
    protected function getAddresses(){
        $addresses = array();
        $entities = $this->getDoctrine()->getManager()->getRepository('ShopMainBundle:Address')->findAll();
        foreach($entities as $entity){
            if($entity instanceof Address){
                $addresses[] = array(
                    'name' => $entity->getName(),
                    'description' => $entity->getDescription(),
                    'phones' => $entity->getPhones(),
                    'work_schedule' => $entity->getWorkSchedule(),

src/Shop/MainBundle/Resources/views/Default/callback.html.twig
{% extends 'ShopMainBundle:Default:v' ~ shop_settings.template_version ~'/callback.html.twig' %}

src/Shop/MainBundle/Resources/views/Default/footer.html.twig
{% extends 'ShopMainBundle:Default:v' ~ shop_settings.template_version ~'/footer.html.twig' %}

src/Shop/MainBundle/Resources/views/Default/header.html.twig
{% extends 'ShopMainBundle:Default:v' ~ shop_settings.template_version ~'/header.html.twig' %}

src/Shop/MainBundle/Resources/views/Default/index.html.twig
{% extends 'ShopMainBundle:Default:v' ~ shop_settings.template_version ~'/index.html.twig' %}

src/Shop/MainBundle/Resources/views/Default/layout.html.twig
{% extends 'ShopMainBundle:Default:v' ~ shop_settings.template_version ~'/layout.html.twig' %}

src/Shop/MainBundle/Resources/views/Default/proposals-left-bar.html.twig
<h1 class="title">
    Каталог
</h1>
<ul class="left-bar-menu">
    {% for _category in categories %}
        <li>
            <div class="btn default medium {{ _category.id == category.id ? 'active' : '' }}">
                <a href="{{ path('shop_category', {'slug' : _category.slug}) }}">
                    {{ _category.name }}
                </a>
            </div>
        </li>
    {% endfor %}
</ul>

src/Shop/MainBundle/Resources/views/Default/proposals.html.twig
{% extends 'ShopMainBundle:Default:layout.html.twig' %}
{% block title %}{{ page.seoTitle|default(category.name) }}{% endblock %}
{% block description %}{{ page.seoDescription|default(category.name) }}{% endblock %}
{% block keywords %}{{ page.seoKeywords|default(category.name) }}{% endblock %}
{% block main_container %}
    <div class="row well-v">
        <div class="three columns">
            {% block proposals_left_bar %}
                {% include('ShopMainBundle:Default:shopCart.html.twig') %}
                {% include('ShopMainBundle:Default:proposals-left-bar.html.twig') %}
                {% if extraParametersData or (priceIntervalsData is defined and priceIntervalsData.intervals) %}
                    <div class="filters-form-container extraFiltersForm-container">
                        <div class="title">
                            Дополнительные фильтры
                        </div>
                        <form id="extraFiltersForm" class="extraFiltersForm">
                            {% if (priceIntervalsData is defined and priceIntervalsData.intervals) %}
                                <div class="proposal-select">
                                    <label for="prices">
                                        Цена
                                    </label>
                                    <div class="checkboxes">
                                        <input type="hidden" name="prices[]" value="-1">
                                        {% for intervalData in priceIntervalsData.intervals %}
                                            <label for="priceStep{{ intervalData.priceStep }}">
                                                <input name="prices[]" id="priceStep{{ intervalData.priceStep }}" value="{{ intervalData.priceStep }}" type="checkbox" {{ intervalData.priceStep in filteredPrices ? "checked='checked'" : "" }} {{ intervalData.proposalsAmount <= 0 ? "disabled='disabled'" : "" }}>
                                                {% if intervalData.priceStep > 0 %}
                                                    {{ intervalData.priceStep|weasty_price }}
                                                    -
                                                {% else %}
                                                    до
                                                {% endif %}
                                                {{ (intervalData.priceStep + priceIntervalsData.interval)|weasty_price }}
                                                <small class="amount">
                                                    ({{ intervalData.proposalsAmount|default(0) }})
                                                </small>
                                            </label>
                                        {% endfor %}
                                    </div>
                                </div>
                            {% endif %}
                            {% for parameterData in extraParametersData %}
                                <div class="proposal-select">
                                    <label for="parameter_{{ parameterData.parameter.id }}">
                                        {{ parameterData.parameter.name }}
                                    </label>
                                    {% if parameterData.parameter.type == constant('TYPE_SELECT', parameterData.parameter) %}
                                        <div class="picker-box">
                                            <div class="picker">
                                                <select id="parameter_{{ parameterData.parameter.id }}" name="parameters[{{ parameterData.parameter.id }}]">
                                                    <option value="-1">Не важно</option>
                                                    {% for option in parameterData.options %}
                                                        {% set optionAmounts = parametersOptionsAmounts[parameterData.parameter.id][option.id] %}
                                                        <option value="{{ option.id }}" {{ filteredParameterValues[parameterData.parameter.id] == option.id ? "selected='selected'" : "" }} {{ optionAmounts.proposalsAmount <= 0 ? "disabled='disabled'" : "" }}>
                                                            {{ option.name }} ({{ optionAmounts.proposalsAmount|default(0) }})
                                                        </option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </div>
                                    {% elseif parameterData.parameter.type == constant('TYPE_CHECKBOXES', parameterData.parameter) %}
                                        <div class="checkboxes">
                                            <input type="hidden" name="parameters[{{ parameterData.parameter.id }}][]" value="-1">
                                            {% for option in parameterData.options %}
                                                {% set optionAmounts = parametersOptionsAmounts[parameterData.parameter.id][option.id] %}
                                                <label for="parameterOption{{ option.id }}">
                                                    <input name="parameters[{{ parameterData.parameter.id }}][]" id="parameterOption{{ option.id }}" value="{{ option.id }}" type="checkbox" {{ (filteredParameterValues[parameterData.parameter.id] == option.id or option.id in filteredParameterValues[parameterData.parameter.id]) ? "checked='checked'" : "" }} {{ optionAmounts.proposalsAmount <= 0 ? "disabled='disabled'" : "" }}>
                                                    {{ option.name }}
                                                    <small class="amount">
                                                        ({{ optionAmounts.proposalsAmount|default(0) }})
                                                    </small>
                                                </label>
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </form>
                    </div>
                {% endif %}
            {% endblock %}
        </div>
        <div class="nine columns">
            {% block proposals_main_container %}
                {% if parametersData or (manufacturers and manufacturers|length > 1) %}
                    <div class="">
                        <div class="filters-form-container">
                            <div class="title">
                                Подбор {{ category.singular_genitive_name }}
                            </div>
                            <form id="filtersForm" class="mainFiltersForm">
                                <ul class="tiles two_up">
                                    {% if manufacturers and manufacturers|length > 1 %}
                                        <li>
                                            <div class="proposal-select">
                                                <label for="manufacturers">
                                                    Производитель
                                                </label>
                                                <div class="picker">
                                                    <select id="manufacturers" name="manufacturer">
                                                        <option value="">Не важно</option>
                                                        {% for manufacturer in manufacturers %}
                                                            <option value="{{ manufacturer.id }}" {{ filteredManufacturer == manufacturer.id ? "selected='selected'" : "" }}>
                                                                {{ manufacturer.name }}
                                                            </option>
                                                        {% endfor %}
                                                    </select>
                                                </div>
                                            </div>
                                        </li>
                                    {% endif %}
                                    {% for parameterData in parametersData %}
                                        <li>
                                            <div class="proposal-select">
                                                <label for="parameter_{{ parameterData.parameter.id }}">
                                                    {{ parameterData.parameter.name }}
                                                </label>
                                                <div class="picker">
                                                    <select id="parameter_{{ parameterData.parameter.id }}" name="parameters[{{ parameterData.parameter.id }}]">
                                                        <option value="-1">Не важно</option>
                                                        {% for option in parameterData.options %}
                                                            {% if parametersOptionsAmounts[parameterData.parameter.id][option.id] is defined %}
                                                                {% set optionAmounts = parametersOptionsAmounts[parameterData.parameter.id][option.id] %}
                                                                <option value="{{ option.id }}" {{ (filteredParameterValues[parameterData.parameter.id] is defined and filteredParameterValues[parameterData.parameter.id] == option.id) ? "selected='selected'" : "" }} {{ optionAmounts.proposalsAmount <= 0 ? "disabled='disabled'" : "" }}>
                                                                    {{ option.name }} ({{ optionAmounts.proposalsAmount|default(0) }})
                                                                </option>
                                                            {% endif %}
                                                        {% endfor %}
                                                    </select>
                                                </div>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </form>
                        </div>
                    </div>
                {% endif %}
                <ul class="proposals-list tiles three_up">
                    {% for proposalData in proposals %}

                        <li class="proposal">

                            {% set proposal = proposalData.proposal %}

                            <a href="{{ path('shop_proposal', { 'categorySlug' : category.slug, 'slug' : proposal.seoSlug|default(proposal.id) }) }}" class="proposal-fancybox inner-container" data-fancybox-type="ajax" rel="proposals">

                                <span class="image-container">
                                    <span class="nailthumb-container">
                                        <img src="{{ proposal.thumbImageUrl|default(proposal.imageUrl) }}">
                                    </span>
                                </span>

                                <span class="title">
                                    {{ proposal.title|nl2br }}
                                </span>

                                <span class="description">
                                    {{ proposal.shortDescription|nl2br }}
                                    {#<br/>#}
                                    {#{{ proposalData.valuesAmount }}#}
                                    {#<br/>#}
                                    {#{% for parameterValue in proposal.parameterValues %}#}
                                        {#<span style="font-weight: bold">#}
                                            {#{{ parameterValue.parameter.name }} - {{ parameterValue.option.name }}#}
                                        {#</span>#}
                                        {#<br/>#}
                                    {#{% endfor %}#}
                                </span>

                                <span class="price">
                                    {% if proposalData.maxPrice > proposalData.price %}
                                        от
                                    {% endif %}
                                    {{ proposalData.price|shop_price }}
                                </span>

                            </a>

                        </li>

                    {% endfor %}

                </ul>
            {% endblock %}
            {% if (page is defined and page) %}
                {{ page.content|nl2br }}
            {% endif %}
        </div>
    </div>
    <script>
        $(function(){

            var $filtersForm = $('#filtersForm, #extraFiltersForm');

            var categoryUrl = '{{ path('shop_category', {'slug' : category.slug}) }}';

            $(':input', $filtersForm).change(function(){

                document.location = categoryUrl + '?' +$filtersForm.serialize();

            });

        });
    </script>
{% endblock %}

src/Shop/MainBundle/Resources/views/Default/shopCart.html.twig
{% if shopCart.priceIds %}
    <h1 class="title">
        Корзина
    </h1>
    <div class="shop-cart">
        {% for categoryData in shopCart.categories %}
            <div class="shop-cart-category">
                <a href="{{ path('shop_catalog_category', {'slug':categoryData.category.slug}) }}">
                    {{ categoryData.category.name }}
                </a>
            </div>
            <div class="shop-cart-category-proposals">
                {% for proposalData in categoryData.proposals %}
                    <div class="shop-cart-category-proposal">
                        <div class="shop-cart-proposal-name">
                            <a href="{{ shop_catalog_proposal_url(proposal) }}">
                                {{ proposalData.proposal.title }}
                            </a>
                        </div>
                        <div class="shop-cart-proposal-prices">
                            {% for priceData in proposalData.prices %}
                                <div class="shop-cart-proposal-price">
                                    <span class="tooltip" title="{{ priceData.price.description|default('Нет описания') }}">
                                        <i class="icon-info"></i>
                                        <span class="price">
                                            {{ priceData.value|weasty_price }}
                                        </span>
                                    </span>
                                    {% if priceData.amount > 1 %}
                                        x
                                        {{ priceData.amount }}
                                        <div class="price-summary">
                                            {{ priceData.summary|weasty_price }}
                                        </div>
                                    {% endif %}
                                    <div class="shop-cart-buttons">

                                        <a href="#" class="add-to-cart" data-cart='{"categoryId":{{ proposalData.proposal.categoryId }},"proposalId":{{ proposalData.proposal.id }},"priceId":{{ priceData.price.id }}}'>
                                            +1
                                        </a>

                                        {% if priceData.amount > 1 %}
                                            <a href="#" class="decrease-amount-in-cart"  data-cart='{"categoryId":{{ proposalData.proposal.categoryId }},"proposalId":{{ proposalData.proposal.id }},"priceId":{{ priceData.price.id }}}'>
                                                -1
                                            </a>
                                        {% endif %}

                                        <a href="#" class="remove-from-cart" data-cart='{"categoryId":{{ proposalData.proposal.categoryId }},"proposalId":{{ proposalData.proposal.id }},"priceId":{{ priceData.price.id }}}'>
                                            Убрать
                                        </a>

                                    </div>

                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <div class="shop-cart-summary">
            {{ shopCart.summaryPrice|weasty_price }}
        </div>
        <a href="{{ path('shop_cart') }}" class="purchase-btn">
            Купить
        </a>
    </div>
{% endif %}